language: node_js
node_js:
  - "10.15.2"
dist: trusty
sudo: false

addons:
  chrome: stable

#branches:
#  only:
#    - master

cache: npm

script:
  - cd angular
  - npm ci
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
