language: node_js
node_js:
  - "10.15.2"
dist: trusty
sudo: false

services:
  - docker

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  #chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build
